# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_score', models.DecimalField(blank=True, decimal_places=2, help_text='Điểm quá trình (0-10)', max_digits=4, null=True)),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, help_text='Điểm giữa kỳ (0-10)', max_digits=4, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Điểm cuối kỳ (0-10)', max_digits=4, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng kết (auto)', max_digits=4, null=True)),
                ('grade_letter', models.CharField(blank=True, help_text='A/B/C/D/F', max_length=2)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Điểm',
                'verbose_name_plural': 'Điểm',
            },
        ),
    ]
