# Generated by Django 5.1.4 on 2026-05-13 07:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm cuối kỳ (0-10)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm giữa kỳ (0-10)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='process_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm quá trình (0-10)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
    ]
