# Generated by Django 5.1.4 on 2026-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_final_score_alter_grade_midterm_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='gpa_4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA thang 4 (auto, plan §7.2.13).', max_digits=3, null=True),
        ),
    ]
