# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(help_text='MSSV, vd: 21520001', max_length=16, unique=True)),
                ('enrollment_year', models.PositiveSmallIntegerField(help_text='Khoá tuyển sinh, vd: 2021')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed_credits', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='majors.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(help_text='Mã GV, vd: GV-0142', max_length=16, unique=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, help_text='Học hàm/học vị, vd: TS., ThS.', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'ordering': ['teacher_code'],
            },
        ),
    ]
