# Generated by Django 5.1.4 on 2026-05-13 07:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Thang điểm 10', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
    ]
