# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: CNTT-2021', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cohort_year', models.PositiveSmallIntegerField(help_text='Khoá áp dụng, vd: 2021')),
                ('total_credits_required', models.PositiveSmallIntegerField(default=145)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculums', to='majors.major')),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Chương trình đào tạo',
                'ordering': ['-cohort_year', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_block', models.CharField(choices=[('GENERAL', 'Đại cương'), ('BASIC', 'Cơ sở ngành'), ('MAJOR', 'Chuyên ngành'), ('ELECTIVE', 'Tự chọn'), ('THESIS', 'Tốt nghiệp')], default='MAJOR', max_length=16)),
                ('is_required', models.BooleanField(default=True, help_text='Bắt buộc / tự chọn')),
                ('suggested_semester', models.PositiveSmallIntegerField(default=1, help_text='Học kỳ gợi ý 1-8')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_links', to='courses.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='curriculums.curriculum')),
            ],
            options={
                'verbose_name': 'Môn học trong CTĐT',
                'verbose_name_plural': 'Môn học trong CTĐT',
                'ordering': ['curriculum', 'suggested_semester', 'course__code'],
                'unique_together': {('curriculum', 'course')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='curriculums', through='curriculums.CurriculumCourse', to='courses.course'),
        ),
    ]
