# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('profiles', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã đăng ký'), ('CANCELLED', 'Đã huỷ')], default='PENDING', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='classes.classsection')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='semesters.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Đăng ký môn',
                'verbose_name_plural': 'Đăng ký môn',
                'ordering': ['-registered_at'],
                'unique_together': {('student', 'class_section')},
            },
        ),
    ]
