# Generated by Django 5.1.4 on 2026-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classsection_teacher_and_more'),
        ('profiles', '0002_alter_studentprofile_gpa'),
        ('registrations', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['student', 'semester'], name='reg_student_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['class_section', 'status'], name='reg_cs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['semester', 'status'], name='reg_sem_status_idx'),
        ),
    ]
