# Generated by Django 5.1.4 on 2026-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: CNTT, KTPM, HTTT', max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, help_text='Khoa quản lý', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ngành đào tạo',
                'verbose_name_plural': 'Ngành đào tạo',
                'ordering': ['code'],
            },
        ),
    ]
