# Generated by Django 5.1.4 on 2026-05-13 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_seed_default_majors'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=4, help_text='Số năm đào tạo (plan §7.2.4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
