# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: CS101, MA202', max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('theory_hours', models.PositiveSmallIntegerField(default=0)),
                ('practice_hours', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='courses.course')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_by_links', to='courses.course')),
            ],
            options={
                'verbose_name': 'Môn tiên quyết',
                'verbose_name_plural': 'Môn tiên quyết',
                'unique_together': {('course', 'required_course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependents', through='courses.Prerequisite', to='courses.course'),
        ),
    ]
