# Generated by Django 5.1.4 on 2026-05-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: CS201.01', max_length=24, unique=True)),
                ('max_students', models.PositiveSmallIntegerField(default=50)),
                ('enrolled_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng'), ('CANCELLED', 'Đã huỷ')], default='DRAFT', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='courses.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='semesters.semester')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Lớp học phần',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')])),
                ('time_slot', models.CharField(choices=[('M1', 'Sáng 1 (07:00-09:00)'), ('M2', 'Sáng 2 (09:00-11:30)'), ('A1', 'Chiều 1 (13:00-15:00)'), ('A2', 'Chiều 2 (15:00-17:30)'), ('E1', 'Tối (18:00-20:30)')], max_length=4)),
                ('room', models.CharField(blank=True, help_text='VD: B4.12', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.classsection')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'ordering': ['class_section', 'weekday', 'time_slot'],
            },
        ),
    ]
