# Generated by Django 5.1.4 on 2026-05-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0002_alter_course_credits_alter_course_practice_hours_and_more'),
        ('profiles', '0002_alter_studentprofile_gpa'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Plan §7.2: MUST có teacher khi lớp được OPEN (validate qua clean()).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='profiles.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['semester', 'status'], name='cls_sem_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['course', 'semester'], name='cls_course_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['weekday', 'time_slot'], name='schedule_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('class_section', 'weekday', 'time_slot'), name='unique_schedule_slot'),
        ),
    ]
