# Generated by Django 5.1.4 on 2026-05-13 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classsection_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['class_section', 'weekday', 'start_period'], 'verbose_name': 'Lịch học', 'verbose_name_plural': 'Lịch học'},
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_schedule_slot',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_slot_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='classsection',
            name='periods_per_session',
            field=models.PositiveSmallIntegerField(default=3, help_text='Số tiết mỗi buổi học (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_period',
            field=models.PositiveSmallIntegerField(default=3, editable=False, help_text='Tiết kết thúc, tự tính theo số tiết mỗi buổi.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Sáng'), ('AFTERNOON', 'Chiều'), ('EVENING', 'Tối')], default='MORNING', max_length=16),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_period',
            field=models.PositiveSmallIntegerField(default=1, help_text='Tiết bắt đầu trong ngày (1-15).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['weekday', 'start_period'], name='schedule_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('class_section', 'weekday', 'start_period'), name='unique_schedule_start_period'),
        ),
    ]
