# Generated by Django 5.1.4 on 2026-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: 2025-2026-HK1', max_length=24, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(choices=[('SPRING', 'Học kỳ 1'), ('SUMMER', 'Học kỳ 3'), ('FALL', 'Học kỳ 2')], max_length=8)),
                ('academic_year', models.CharField(help_text='VD: 2025-2026', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False, help_text='Học kỳ đang mở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
                'ordering': ['-start_date'],
            },
        ),
    ]
